version: '3.8'

services:
  notionnext:
    # 使用镜像,而非重新构建
    image: notionnext:latest        # 使用上传的镜像

    # 使用本地Dockerfile构建镜像
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    # 容器名称
    container_name: notionnext

    # 端口映射：宿主机端口:容器端口
    ports:
      - "3000:3000"

    # 环境变量（从.env文件读取）
    environment:
      - NOTION_PAGE_ID=${NOTION_PAGE_ID}
      - NEXT_PUBLIC_THEME=${NEXT_PUBLIC_THEME:-hexo}
      - NEXT_PUBLIC_LANG=${NEXT_PUBLIC_LANG:-zh-CN}
      - NEXT_PUBLIC_TITLE=${NEXT_PUBLIC_TITLE}
      - NEXT_PUBLIC_AUTHOR=${NEXT_PUBLIC_AUTHOR}
      - NEXT_PUBLIC_BIO=${NEXT_PUBLIC_BIO}
      - NODE_ENV=production

    # 挂载配置文件（可选）
    volumes:
      - ./blog.config.js:/app/blog.config.js:ro

    # 重启策略
    restart: always

    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # 网络配置（如需与其他服务通信）
    networks:
      - notion-network

# 定义网络
networks:
  notion-network:
    driver: bridge

